#ifndef CONFIG_H
#define CONFIG_H

#define ADC_CONVERSION (1024/2.56)
#define BATT_FULL 300
#define BATT_FULL_HYSTERESIS 300
#define BATT_ALMOST_FULL 300
#define BATT_MID 300
#define BATT_LOW 300


#define CHARGER_PLUGGED_IN  (PINB&(1<<PINB6))
#define CHARGER_TO_BATTERY_RELAY_ON
#define CHARGER_TO_BATTERY_RELAY_OFF
#define BATTERY_TO_OUT_RELAY_ON
#define BATTERY_TO_OUT_RELAY_OFF
#define COOLER_ON
#define COOLER_OFF

#endif